extends:
 - ./lint/eslintrc-gjs.yml
 - ./lint/eslintrc-shell.yml

overrides:
  - files: ./*.js
    globals:
      global: readonly
      _: readonly
      C_: readonly
      N_: readonly
      ngettext: readonly

    rules:
      consistent-return:
        - warn
      no-invalid-this:
        - warn
      no-return-assign:
        - warn
      no-unused-vars:
        - warn
