extends:
 - ./lint/eslintrc-gjs.yml
 - ./lint/eslintrc-shell.yml

overrides:
  - files: ./*.js
    globals:
      global: readonly
      _: readonly
      C_: readonly
      N_: readonly
      ngettext: readonly
