---
name: Make
'on':
  pull_request:
  push:
    branches:
      - master
      - ubuntu-dock
      - make_ci
    tags:
      - 'extensions.gnome.org-v*'

jobs:
  make:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Install dependencies.
        run: sudo apt-get install -y sassc gettext

      - name: Make
        run: make

      - name: Install modules
        run: sudo npm install eslint@9.x -g

      - name: Make Check
        run: make check

      - name: Make Install
        run: make install

      - name: Generate translations
        run: make potfile

  shexli:
    name: shexli
    runs-on: ubuntu-latest
    if: >-
      (github.event_name == 'pull_request' &&
       github.base_ref == 'master') ||
      github.ref == 'refs/heads/master' ||
      startsWith(github.ref, 'refs/tags/extensions.gnome.org-v')
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Install dependencies.
        run: sudo apt-get install -y sassc gettext

      - name: Build extension
        run: make _build && (cd _build && zip -qr ../extension.zip .)

      - name: Run shexli
        uses: 3v1n0/shexli-ci@main
        with:
          path: extension.zip
          baseline: shexli-baseline.json

